[package]
name = "zcash_ffi"
version = "0.1.0"
edition = "2024"

[dependencies]
incrementalmerkletree = { version = "0.8.2", default-features = false }
orchard = { git = "https://github.com/aCinal/orchard", branch = "add_spends_with_alphas", default-features = false, features = ["circuit"] }
pasta_curves = { version = "0.5.1", default-features = false }
rand_core = { version = "0.6", default-features = false }
sgx = { version = "0.1.0", path = "../sgx" }
zcash_note_encryption = { version = "0.4.1", default-features = false }
zcash_primitives = { version = "0.27.0", default-features = false }
zcash_protocol = { version = "0.8.0", default-features = false }

[patch.crates-io]
orchard = { git = "https://github.com/aCinal/orchard", branch = "add_spends_with_alphas" }

[lib]
crate-type = ["staticlib"]

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
