
#ifndef __SRC_OPERATOR_UNTRUSTED_UNTRUSTED_GLUE_CODE_H
#define __SRC_OPERATOR_UNTRUSTED_UNTRUSTED_GLUE_CODE_H

#include "auntie_operator_u.h"

#endif /* __SRC_OPERATOR_UNTRUSTED_UNTRUSTED_GLUE_CODE_H */
